#Workflow for deploying static content to GitHub Pages
name: Build and GH-Page Deploy

on:
  push:
    branches: ["master"]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
          persist-credentials: false
          lfs: true

      - name: Install
        run: npm install

      - name: Build
        run: |
          npm run lint
          npm run update-tle
          npm run build
          
      - name: Deploy to GH Page
        uses: JamesIves/github-pages-deploy-action@v4.4.3
        with:
          branch: gh-pages
          folder: dist
          exclude_assets: '.github,**/.gitignore'
